name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Download skia
        run: |
          curl -sLo skia.zip https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
          mkdir C:\deps\skia
          tar -xf skia.zip -C C:\deps\skia
      - uses: aseprite/get-ninja@main
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Workaround for windows-2022 and cmake 3.25.0
        shell: bash
        run: rm -rf C:/Strawberry/
      - name: Generating Makefiles
        shell: bash
        run: |
          export skia_arch=x64
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DENABLE_SCRIPTING=on \
            -DENABLE_CCACHE=off \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=C:/deps/skia \
            -DSKIA_LIBRARY_DIR=C:/deps/skia/out/Release-x64 \
            -DSKIA_LIBRARY=C:/deps/skia/out/Release-x64/skia.lib \
      - name: Compiling
        shell: bash
        run: |
          cd build && ninja aseprite
      - uses: actions/upload-artifact@v3
        with:
          name: aseprite
          path: build/bin/
